#Comentários de metadados da aplicação. NÃO EDITAR MANUALMENTE.
#Tue Dec 02 21:48:58 WET 2025
ALUNOS=Agrega dados b\u00E1sicos de ALUNO com IDADE e FOTO
LISTA=Lista principal de ALUNOS, incluindo idade e hist\u00F3rico de inscri\u00E7\u00F5es
VISTA=Coment\u00E1rio da vista
IULTIMOTRIMESTRE=Filtra inscri\u00E7\u00F5es do ULTIMO TRIMESTRE (ANTERIOR) em rela\u00E7\u00E3o \u00E0 data atual
INSCRICOES=Lista a \u00FAltima inscri\u00E7\u00E3o, em cada disciplina, com NOTA NULL (inscri\u00E7\u00F5es ativas/pendentes)
AVALIACOES=Retorna a MELHOR NOTA obtida, por cada ALUNO, DISCIPLINA no MIN(ANO)
