services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test
      # uncomment below if you want to automatically create and select a database
      # MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"